modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/Balm/issues"
[[mods]]
modId="balm"
version="${file.jarVersion}"
displayName="Balm"
displayURL="https://mods.twelveiterations.com/"
logoFile="balm-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Abstraction Layer (but not really)â„¢ for Blay's multiplatform mods
'''
[[dependencies.balm]]
    modId="forge"
    mandatory=true
    versionRange="[46.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.balm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
