modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/TwelveIterationMods/Balm/issues"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://mods.twelveiterations.com/"
logoFile="${mod_id}.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
